site_name: Paycorp Functional Documentation
theme:
  name: material
nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Creatinh and Maintaining Mandates': 'mandate.md'
        - 'Setting up Payments': 'payments.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'