site_name: Paycorp Documentation
site_url: https://prashantevolvus.github.io
site_author: Prashant Maroli
site_description: >-
  Paycorp documentation website for all Paycorp customer.

# Repository
repo_name: prashantevolvus/prashantevolvus.github.io
repo_url: https://github.com/prashantevolvus/prashantevolvus.github.io

# Copyright
copyright: Copyright &copy; 2022 - 2024 paycorp

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: deep purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/paycorp-io/
      name: Paycorp on Linkedin
    - icon: fontawesome/brands/github
      link: https://github.com/paycorp-io
      name: Paycorp on Github
nav:
    - Home: 'index.md'
    - 'Setup':
      - 'Getting Started': 'start-setup.md'
      - 'Bank Setup': 'bank-setup.md'
      - 'Corporate Setup': 'corp-setup.md'
    - 'User Guide':
        - 'Mandate Management': 'mandate.md'
        - 'Payments': 'payments.md'
        - 'Administration':
          - 'User Maintenance': 'user.md'
          - 'Role Maintenance': 'role.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
markdown_extensions:
  - tables
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

plugins:
   - minify:
      minify_html: true