site_name: Paycorp Functional Documentation
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Mandate Management': 'mandate.md'
        - 'Payments': 'payments.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'